(* R10 v1 codegen-gate test (adr-0014-wf-checker §4): an ill-scoped tm fed through the
   LIBRARY entry point (Rocqeteer_codegen.Emit.emit_programs — the same code path the
   rocqeteer-codegen CLI drives) must fail LOUDLY with the exact
   "program <name>: ill-formed (wf_tm = false)" message, BEFORE any byte of output; and
   the full single-source list Samples.all_programs must pass the gate and emit the
   standard header. That the emitted bytes for all_programs are UNCHANGED versus the
   committed generated/prog0_generated.ml is asserted by the freshness gate
   (ci/check_generated_fresh.sh), which re-runs the CLI driver over this same library. *)

module E = Ref_extracted.EffIR
module D = Ref_extracted.Datatypes

let coq_name (s : string) : Ref_extracted.String.string =
  Coqconv.coq_string_of_bytes (Bytes.of_string s)

(* Bind (Ret VUnit) (Ret (VVar 2)): VVar 2 under ONE binder — ill-scoped (the
   theories/Wf.v anti-vacuity shape: wf_tm rejects it AND its reference run hits
   Dstuck). *)
let ill_scoped : E.tm =
  E.Bind (E.Ret E.VUnit, E.Ret (E.VVar (D.S (D.S D.O))))

let expected_msg = "program bad_prog: ill-formed (wf_tm = false)"

let () =
  (* 1. The gate REJECTS the ill-scoped program: exact loud message, no output. *)
  let buf = Buffer.create 256 in
  let fmt = Format.formatter_of_buffer buf in
  let progs =
    Coqconv.coq_list_of [ D.Coq_pair (coq_name "bad_prog", ill_scoped) ]
  in
  (match Rocqeteer_codegen.Emit.emit_programs fmt progs with
   | () ->
       prerr_endline "FAIL: ill-scoped program was ACCEPTED by the wf gate";
       exit 1
   | exception Rocqeteer_codegen.Emit.Codegen_error msg ->
       if msg <> expected_msg then begin
         Printf.eprintf "FAIL: unexpected gate message: %S (expected %S)\n"
           msg expected_msg;
         exit 1
       end);
  Format.pp_print_flush fmt ();
  if Buffer.length buf > 0 then begin
    prerr_endline "FAIL: the gate emitted output for a rejected run";
    exit 1
  end;
  (* 2. Every program of the single-source list passes the gate; the standard header
        comes out first (inhabitance side of the gate — it is not a universal
        rejector; mirrors theories/Wf.v wf_all_programs). *)
  let buf2 = Buffer.create 65536 in
  let fmt2 = Format.formatter_of_buffer buf2 in
  (match
     Rocqeteer_codegen.Emit.emit_programs fmt2 Ref_extracted.Samples.all_programs
   with
   | () -> ()
   | exception Rocqeteer_codegen.Emit.Codegen_error msg ->
       Printf.eprintf "FAIL: wf gate rejected a single-source program: %s\n" msg;
       exit 1);
  let out = Buffer.contents buf2 in
  let header_prefix = "(* Generated by rocq-eff-codegen" in
  if String.length out < String.length header_prefix
     || String.sub out 0 (String.length header_prefix) <> header_prefix
  then begin
    prerr_endline "FAIL: emitted output does not start with the standard header";
    exit 1
  end;
  print_endline
    "wf_gate_test OK: ill-scoped rejected loudly (exact message, zero output); \
     all_programs pass the gate with the standard header"
