(** rocq-eff-codegen (slice 1): lower an extracted EffIR [tm] to direct-style OCaml 5.

    The monad is ERASED by construction: [Bind] -> [let], [Perform] -> a [Kv.*] call,
    [MatchOpt] -> [match]. No [Bind]/free-monad constructor survives into the output
    (property P3). Out-of-fragment input fails loudly rather than emitting unsound code
    (kb/spec/codegen.md, kb/spec/error-taxonomy.md).

    Slice-1 scope: it lowers exactly the four [tm] forms and the [val] forms that
    [prog0] needs; anything else raises [Codegen_error]. *)

open Ref_extracted.EffIR

module BinNums = Ref_extracted.BinNums

exception Codegen_error of string

(* The name of the next binder is its de Bruijn DEPTH (= current environment length), so
   names are v0, v1, ... by scope depth: deterministic (byte-stable output, P4/NF5) with no
   global mutable state, and they reset naturally per program (kb/conventions/code-style.md). *)
let bind_name (env : string list) : string = "v" ^ string_of_int (List.length env)

(* A coq_Z literal becomes an exact zarith value via its decimal string (any size). *)
let emit_z (z : BinNums.coq_Z) : string =
  Printf.sprintf "(Z.of_string \"%s\")" (Z.to_string (Coqconv.z_of_coqz z))

(* [env] maps a de Bruijn index (0 = most recent binder) to its OCaml variable name. *)
let rec emit_val (env : string list) (v : coq_val) : string =
  match v with
  | VVar n -> (
      match List.nth_opt env (Coqconv.int_of_nat n) with
      | Some name -> name
      | None -> raise (Codegen_error "VVar index out of scope"))
  | VUnit -> "()"
  | VBool b -> if Coqconv.bool_of_coq b then "true" else "false"
  | VInt z -> emit_z z
  | VNone -> "None"
  | VSome a -> Printf.sprintf "(Some %s)" (emit_val env a)
  | VPair (a, b) -> Printf.sprintf "(%s, %s)" (emit_val env a) (emit_val env b)
  | VZero -> "Z.zero"
  | VSucc a -> Printf.sprintf "(Z.succ %s)" (emit_val env a)

(* KV operations lower to the curried public wrappers (kb/spec/effect-signatures.md,
   Resolution 7). Wrong arity is a codegen error, not a silent cast. *)
let emit_perform (env : string list) (o : op) (args : coq_val list) : string =
  let a = List.map (emit_val env) args in
  match (o, a) with
  | OGet, [ k ] -> Printf.sprintf "(Kv.get %s)" k
  | OPut, [ k; v ] -> Printf.sprintf "(Kv.put %s %s)" k v
  | ODelete, [ k ] -> Printf.sprintf "(Kv.delete %s)" k
  | OThrow, [ e ] -> Printf.sprintf "(Err.throw %s)" e
  | OAsk, [] -> "(Env.ask ())"
  | OTrace, [ v ] -> Printf.sprintf "(Trace.emit %s)" v
  | OCacheGet, [ k ] -> Printf.sprintf "(Cache.get %s)" k
  | OCachePut, [ k; v ] -> Printf.sprintf "(Cache.put %s %s)" k v
  | _ -> raise (Codegen_error "effect operation applied at the wrong arity")

let rec emit_tm (env : string list) (t : tm) : string =
  match t with
  | Ret v -> emit_val env v
  | Bind (t1, t2) ->
      let name = bind_name env in
      Printf.sprintf "(let %s = %s in %s)" name (emit_tm env t1)
        (emit_tm (name :: env) t2)
  | Perform (o, args) -> emit_perform env o (Coqconv.list_of_coq args)
  | MatchOpt (scrut, none, some) ->
      let name = bind_name env in
      Printf.sprintf "(match %s with None -> %s | Some %s -> %s)"
        (emit_val env scrut) (emit_tm env none) name
        (emit_tm (name :: env) some)

let header =
  "(* Generated by rocq-eff-codegen (slice 1). Source: theories/EffIR.v + Samples.v.\n\
  \   Direct-style; the EffIR monad has been erased. Do not edit manually.\n\
  \   See kb/spec/codegen.md. *)\n\
   open Rkv\n"

(* The programs to lower, each as one direct-style [name : unit -> _]. prog0 is the
   slice example; the samples cover ODelete / Ret / multi-Perform / negative literal /
   deep de Bruijn nesting so those lowering rules are differentially tested, not dead. *)
let programs : (string * tm) list =
  [ ("prog0", prog0);
    ("sample_delete", Ref_extracted.Samples.sample_delete);
    ("sample_two", Ref_extracted.Samples.sample_two);
    ("sample_ret", Ref_extracted.Samples.sample_ret);
    ("sample_neg", Ref_extracted.Samples.sample_neg);
    ("sample_nested", Ref_extracted.Samples.sample_nested);
    ("sample_throw", Ref_extracted.Samples.sample_throw);
    ("sample_guard5", Ref_extracted.Samples.sample_guard5);
    ("sample_env", Ref_extracted.Samples.sample_env);
    ("sample_trace", Ref_extracted.Samples.sample_trace);
    ("sample_cache", Ref_extracted.Samples.sample_cache) ]

(* Emit all programs to stdout (captured by the dune rule into generated/). *)
let () =
  print_string header;
  List.iter
    (fun (name, t) -> Printf.printf "let %s () = %s\n" name (emit_tm [] t))
    programs
