#!/usr/bin/env bash
# Generate docs/tcb_report.md from live build facts (kb/spec/runtime-manifest.md).
set -eu
cd "$(dirname "$0")/.."
out=docs/tcb_report.md

rocqv=$(rocq --version 2>/dev/null | head -1 || true)
ocamlv=$(ocaml --version 2>/dev/null || true)
dunev=$(dune --version 2>/dev/null || true)

# Capture `Print Assumptions incr_correct` via a throwaway file compiled against the
# built theory (keeps the source tree clean - no stray .glob/.vo next to sources).
dune build theories/ >/dev/null 2>&1
tmpd=$(mktemp -d)
printf 'From Rocqeteer Require Import KV.\nPrint Assumptions incr_correct.\n' > "$tmpd/Check.v"
assum=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/Check.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
rm -rf "$tmpd"
[ -z "$assum" ] && assum="(capture failed)"

dune build extraction/ generated/ >/dev/null 2>&1 || true
objmagic=$(grep -rl "Obj.magic" _build/default/extraction _build/default/generated codegen runtime support tests generated 2>/dev/null | wc -l | tr -d ' ')
admitted=$(grep -rlE 'Admitted\.|(^|[^[:alnum:]_])admit([^[:alnum:]_]|$)' theories 2>/dev/null | wc -l | tr -d ' ')
genfile=$(find _build/default/generated -name '*_generated.ml' 2>/dev/null | head -1 || true)
bind=0; [ -n "$genfile" ] && bind=$(grep -cE '\bBind\b' "$genfile" || true)

{
echo "# TCB report — Rocqeteer (slice 1)"
echo
echo "_Generated by ci/gen_tcb_report.sh. Do not edit by hand._"
echo
echo "## Toolchain"
echo "- Rocq: ${rocqv}"
echo "- OCaml: ${ocamlv}"
echo "- dune: ${dunev}"
echo
echo "## Proof TCB"
echo "- \`Print Assumptions incr_correct\`: **${assum}**"
echo "- Admitted/admit files in theories/: **${admitted}** (must be 0)"
echo "- Rocq Axioms declared: **0** (refinement is a documented manifest assumption, not a Rocq axiom)"
echo
echo "## Extraction / runtime TCB"
echo "- \`Obj.magic\` occurrences (extracted + sources): **${objmagic}** (budget 0)"
echo "- Free-monad \`Bind\` constructors in generated code: **${bind}** (must be 0, property P3)"
echo "- Trusted: Rocq extraction, rocq-eff-codegen, OCaml compiler+runtime, Effect.Deep handlers, Rkv runtime."
echo
echo "## Realizers & assumptions (docs/runtime_manifest.toml)"
echo "| name | kind | ocaml | validated_by |"
echo "|------|------|-------|--------------|"
echo "| value_zero | primitive | Z.zero | diff_kv |"
echo "| value_succ | primitive | Z.succ | diff_kv |"
echo "| KV (Get/Put/Delete) | effect | Rkv.Kv | diff_test, diff_kv |"
echo "| Runtime_KV_refines | assumption (tcb-assumption) | reference == fast | diff_test, diff_kv (5000 adversarial) |"
echo "| Error (Throw) | effect | Rkv.Err | diff_err |"
echo "| Runtime_Error_refines | assumption (tcb-assumption) | abort outcome+state | diff_err (3000) |"
echo "| Env (Ask) | effect | Rkv.Env | diff_env |"
echo "| Runtime_Env_refines | assumption (tcb-assumption) | read-only ctx flows | diff_env (3000) |"
echo "| Trace (Emit) | effect | Rkv.Trace | diff_trace |"
echo "| Runtime_Trace_refines | assumption (tcb-assumption) | event log in order | diff_trace (3000) |"
echo "| Cache (CGet/CPut) | effect | Rkv.Cache | diff_cache |"
echo "| Runtime_Cache_invisible | assumption (tcb-assumption) | hit == miss (invisible) | diff_cache (3000) |"
echo "| Codec | typed-witness realizer (GADT, no casts) | Rkv.Codec | codec_test; proven in Codec.v |"
echo
echo "## Public effectful entrypoints"
echo "- \`Generated.Prog0_generated.prog0\` under \`Rkv.Kv.run\`/\`run_checked\` (unhandled -> typed error, T8)."
echo "- error programs (sample_throw/sample_guard5) under \`Err.run_error (Kv.run …)\` (throw -> Error e, aborts)."
echo
echo "## Forbidden-API gates (CI)"
echo "- no Obj.magic; Effect.perform confined to runtime/; no Admitted/admit/Axiom; no unregistered Extract Constant; generated file unedited."
} > "$out"
echo "wrote $out"
