#!/usr/bin/env bash
# Generate docs/tcb_report.md from live build facts (kb/spec/runtime-manifest.md).
set -eu
cd "$(dirname "$0")/.."
out=docs/tcb_report.md

rocqv=$(rocq --version 2>/dev/null | head -1 || true)
ocamlv=$(ocaml --version 2>/dev/null || true)
dunev=$(dune --version 2>/dev/null || true)

# Capture `Print Assumptions incr_correct`, `Print Assumptions bytes_correct`,
# and `Print Assumptions parse_print_roundtrip` (R3 prim round-trip, all in-range z)
# via throwaway files compiled against the built theory (keeps the source tree clean).
dune build theories/ >/dev/null 2>&1
tmpd=$(mktemp -d)
printf 'From Rocqeteer Require Import KV.\nPrint Assumptions incr_correct.\n' > "$tmpd/Check.v"
assum=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/Check.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import BytesVal.\nPrint Assumptions bytes_correct.\n' > "$tmpd/CheckB.v"
assum_bytes=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckB.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import Prims.\nPrint Assumptions parse_print_roundtrip.\n' > "$tmpd/CheckP.v"
assum_prims=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckP.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import StructVal.\nPrint Assumptions tag_build_success.\n' > "$tmpd/CheckS.v"
assum_structval=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckS.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
rm -rf "$tmpd"
[ -z "$assum" ] && assum="(capture failed)"
[ -z "$assum_bytes" ] && assum_bytes="(capture failed)"
[ -z "$assum_prims" ] && assum_prims="(capture failed)"
[ -z "$assum_structval" ] && assum_structval="(capture failed)"

dune build extraction/ generated/ >/dev/null 2>&1 || true
objmagic=$(grep -rl "Obj.magic" _build/default/extraction _build/default/generated codegen runtime support tests generated 2>/dev/null | wc -l | tr -d ' ')
admitted=$(grep -rlE 'Admitted\.|(^|[^[:alnum:]_])admit([^[:alnum:]_]|$)' theories 2>/dev/null | wc -l | tr -d ' ')
genfile=$(find _build/default/generated -name '*_generated.ml' 2>/dev/null | head -1 || true)
bind=0; [ -n "$genfile" ] && bind=$(grep -cE '\bBind\b' "$genfile" || true)

{
echo "# TCB report — Rocqeteer (slice 1)"
echo
echo "_Generated by ci/gen_tcb_report.sh. Do not edit by hand._"
echo
echo "## Toolchain"
echo "- Rocq: ${rocqv}"
echo "- OCaml: ${ocamlv}"
echo "- dune: ${dunev}"
echo
echo "## Proof TCB"
echo "- \`Print Assumptions incr_correct\`: **${assum}**"
echo "- \`Print Assumptions bytes_correct\`: **${assum_bytes}**"
echo "- \`Print Assumptions parse_print_roundtrip\`: **${assum_prims}**"
echo "- \`Print Assumptions tag_build_success\`: **${assum_structval}**"
echo "- Admitted/admit files in theories/: **${admitted}** (must be 0)"
echo "- Rocq Axioms declared: **0** (refinement is a documented manifest assumption, not a Rocq axiom)"
echo
echo "## Extraction / runtime TCB"
echo "- \`Obj.magic\` occurrences (extracted + sources): **${objmagic}** (budget 0)"
echo "- Free-monad \`Bind\` constructors in generated code: **${bind}** (must be 0, property P3)"
echo "- Trusted: Rocq extraction, rocq-eff-codegen, OCaml compiler+runtime, Effect.Deep handlers, Rkv runtime."
echo
echo "## Realizers & assumptions (docs/runtime_manifest.toml)"
echo "| name | kind | ocaml | validated_by |"
echo "|------|------|-------|--------------|"
echo "| value_zero | primitive | Z.zero | diff_kv |"
echo "| value_succ | primitive | Z.succ | diff_kv |"
echo "| value_bytes | primitive | Rval.Bytes (Bytes.of_string ...) | diff_bytes |"
echo "| prim_add_checked | primitive | Prims.prim_add_checked | diff_prims |"
echo "| prim_sub_checked | primitive | Prims.prim_sub_checked | diff_prims |"
echo "| prim_cmp_int | primitive | Prims.prim_cmp_int | diff_prims |"
echo "| prim_eq_bytes | primitive | Prims.prim_eq_bytes | diff_prims |"
echo "| prim_bytes_len | primitive | Prims.prim_bytes_len | diff_prims |"
echo "| prim_bytes_concat | primitive | Prims.prim_bytes_concat | diff_prims |"
echo "| prim_bytes_sub | primitive | Prims.prim_bytes_sub | diff_prims |"
echo "| prim_parse_int64 | primitive | Prims.prim_parse_int64 | diff_prims |"
echo "| prim_print_int | primitive | Prims.prim_print_int | diff_prims |"
echo "| Runtime_Prims_refines | assumption (tcb-assumption) | apply_prim == Prims.prim_* | diff_prims (3000 pipeline states G1-G16 + direct per-prim pass, all 9 prims) |"
echo "| value_tag | primitive | Rval.Tag (Z.t, Rval.t) | diff_structval |"
echo "| value_list | primitive | Rval.List (Rval.t list) | diff_structval |"
echo "| Runtime_StructVal_refines | assumption (tcb-assumption) | DTag/DList <-> Rval.Tag/Rval.List bridge + tag_build/tag_dispatch samples | diff_structval (2000+3000 sample states, 2000 fuzzed bridge round-trips, S1-S9 coverage) |"
echo "| KV (Get/Put/Delete) | effect | Rkv.Kv | diff_test, diff_kv |"
echo "| Runtime_KV_refines | assumption (tcb-assumption) | reference == fast | diff_test, diff_kv (5000 adversarial) |"
echo "| Error (Throw) | effect | Rkv.Err | diff_err |"
echo "| Runtime_Error_refines | assumption (tcb-assumption) | abort outcome+state | diff_err (3000) |"
echo "| Env (Ask) | effect | Rkv.Env | diff_env |"
echo "| Runtime_Env_refines | assumption (tcb-assumption) | read-only ctx flows | diff_env (3000) |"
echo "| Trace (Emit) | effect | Rkv.Trace | diff_trace |"
echo "| Runtime_Trace_refines | assumption (tcb-assumption) | event log in order | diff_trace (3000) |"
echo "| Cache (CGet/CPut) | effect | Rkv.Cache | diff_cache |"
echo "| Runtime_Cache_invisible | assumption (tcb-assumption) | hit == miss (invisible) | diff_cache (3000) |"
echo "| Codec | typed-witness realizer (GADT, no casts) | Rkv.Codec | codec_test; proven in Codec.v |"
echo
echo "## Public effectful entrypoints"
echo "- \`Generated.Prog0_generated.prog0\` under \`Rkv.Kv.run\`/\`run_checked\` (unhandled -> typed error, T8)."
echo "- error programs (sample_throw/sample_guard5) under \`Err.run_error (Kv.run …)\` (throw -> Error e, aborts)."
echo
echo "## Forbidden-API gates (CI)"
echo "- no Obj.magic; Effect.perform confined to runtime/; no Admitted/admit/Axiom; no unregistered Extract Constant; generated file unedited."
} > "$out"
echo "wrote $out"
