#!/usr/bin/env bash
# Generate docs/tcb_report.md from live build facts (kb/spec/runtime-manifest.md).
set -eu
cd "$(dirname "$0")/.."
out=docs/tcb_report.md

rocqv=$(rocq --version 2>/dev/null | head -1 || true)
ocamlv=$(ocaml --version 2>/dev/null || true)
dunev=$(dune --version 2>/dev/null || true)

# Capture `Print Assumptions incr_correct`, `Print Assumptions bytes_correct`,
# and `Print Assumptions parse_print_roundtrip` (R3 prim round-trip, all in-range z)
# via throwaway files compiled against the built theory (keeps the source tree clean).
dune build theories/ >/dev/null 2>&1
tmpd=$(mktemp -d)
printf 'From Rocqeteer Require Import KV.\nPrint Assumptions incr_correct.\n' > "$tmpd/Check.v"
assum=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/Check.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import BytesVal.\nPrint Assumptions bytes_correct.\n' > "$tmpd/CheckB.v"
assum_bytes=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckB.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import Prims.\nPrint Assumptions parse_print_roundtrip.\n' > "$tmpd/CheckP.v"
assum_prims=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckP.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import StructVal.\nPrint Assumptions tag_build_success.\n' > "$tmpd/CheckS.v"
assum_structval=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckS.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import TimeStore.\nPrint Assumptions alive_at_deadline.\n' > "$tmpd/CheckT.v"
assum_timestore=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckT.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import Fold.\nPrint Assumptions fold_mixed_end_to_end.\n' > "$tmpd/CheckF.v"
assum_fold=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckF.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
printf 'From Rocqeteer Require Import Journal.\nPrint Assumptions run_journal_frame.\n' > "$tmpd/CheckJ.v"
assum_journal=$(coqc -R _build/default/theories Rocqeteer -output-directory "$tmpd" "$tmpd/CheckJ.v" 2>&1 \
          | grep -iE "closed under the global context|axioms:" | head -1 || true)
rm -rf "$tmpd"
[ -z "$assum" ] && assum="(capture failed)"
[ -z "$assum_bytes" ] && assum_bytes="(capture failed)"
[ -z "$assum_prims" ] && assum_prims="(capture failed)"
[ -z "$assum_structval" ] && assum_structval="(capture failed)"
[ -z "$assum_timestore" ] && assum_timestore="(capture failed)"
[ -z "$assum_fold" ] && assum_fold="(capture failed)"
[ -z "$assum_journal" ] && assum_journal="(capture failed)"

dune build extraction/ generated/ >/dev/null 2>&1 || true
objmagic=$(grep -rl "Obj.magic" _build/default/extraction _build/default/generated codegen runtime support tests generated 2>/dev/null | wc -l | tr -d ' ')
admitted=$(grep -rlE 'Admitted\.|(^|[^[:alnum:]_])admit([^[:alnum:]_]|$)' theories 2>/dev/null | wc -l | tr -d ' ')
genfile=$(find _build/default/generated -name '*_generated.ml' 2>/dev/null | head -1 || true)
bind=0; [ -n "$genfile" ] && bind=$(grep -cE '\bBind\b' "$genfile" || true)

{
echo "# TCB report — Rocqeteer (slice 1)"
echo
echo "_Generated by ci/gen_tcb_report.sh. Do not edit by hand._"
echo
echo "## Toolchain"
echo "- Rocq: ${rocqv}"
echo "- OCaml: ${ocamlv}"
echo "- dune: ${dunev}"
echo
echo "## Proof TCB"
echo "- \`Print Assumptions incr_correct\`: **${assum}**"
echo "- \`Print Assumptions bytes_correct\`: **${assum_bytes}**"
echo "- \`Print Assumptions parse_print_roundtrip\`: **${assum_prims}**"
echo "- \`Print Assumptions tag_build_success\`: **${assum_structval}**"
echo "- \`Print Assumptions alive_at_deadline\` (R4+R5 boundary, live iff now<=d): **${assum_timestore}**"
echo "- \`Print Assumptions fold_mixed_end_to_end\` (R6 Fold, effectful left fold): **${assum_fold}**"
echo "- \`Print Assumptions run_journal_frame\` (R9 Journal frame law, GENERAL — journal is write-only): **${assum_journal}**"
echo "- Admitted/admit files in theories/: **${admitted}** (must be 0)"
echo "- Rocq Axioms declared: **0** (refinement is a documented manifest assumption, not a Rocq axiom)"
echo
echo "## Extraction / runtime TCB"
echo "- \`Obj.magic\` occurrences (extracted + sources): **${objmagic}** (budget 0)"
echo "- Free-monad \`Bind\` constructors in generated code: **${bind}** (must be 0, property P3)"
echo "- Trusted: Rocq extraction, rocq-eff-codegen, OCaml compiler+runtime, Effect.Deep handlers, Rkv runtime."
echo
echo "## Realizers & assumptions (docs/runtime_manifest.toml)"
echo "| name | kind | ocaml | validated_by |"
echo "|------|------|-------|--------------|"
echo "| value_zero | primitive | Z.zero | diff_kv |"
echo "| value_succ | primitive | Z.succ | diff_kv |"
echo "| value_bytes | primitive | Rval.Bytes (Bytes.of_string ...) | diff_bytes |"
echo "| prim_add_checked | primitive | Prims.prim_add_checked | diff_prims |"
echo "| prim_sub_checked | primitive | Prims.prim_sub_checked | diff_prims |"
echo "| prim_cmp_int | primitive | Prims.prim_cmp_int | diff_prims |"
echo "| prim_eq_bytes | primitive | Prims.prim_eq_bytes | diff_prims |"
echo "| prim_bytes_len | primitive | Prims.prim_bytes_len | diff_prims |"
echo "| prim_bytes_concat | primitive | Prims.prim_bytes_concat | diff_prims |"
echo "| prim_bytes_sub | primitive | Prims.prim_bytes_sub | diff_prims |"
echo "| prim_parse_int64 | primitive | Prims.prim_parse_int64 | diff_prims |"
echo "| prim_print_int | primitive | Prims.prim_print_int | diff_prims |"
echo "| prim_mul_checked | primitive | Prims.prim_mul_checked | diff_prims |"
echo "| prim_list_len | primitive | Prims.prim_list_len | diff_prims |"
echo "| prim_list_nth | primitive | Prims.prim_list_nth | diff_prims |"
echo "| prim_div_floor | primitive | Prims.prim_div_floor (Z.fdiv — FLOOR, matching Rocq Z.div; divisor 0 -> None, no exception) | diff_prims |"
echo "| prim_lower_bytes | primitive | Prims.prim_lower_bytes (ASCII fold 65-90 +32, other bytes incl. >127 unchanged; fresh Bytes.map buffer) | diff_prims |"
echo "| prim_upper_bytes | primitive | Prims.prim_upper_bytes (ASCII fold 97-122 -32, other bytes incl. >127 unchanged; fresh Bytes.map buffer) | diff_prims |"
echo "| prim_list_snoc | primitive | Prims.prim_list_snoc (append at the END — vs @ [v]; O(n) per snoc, documented: collecting folds bounded by the consumer's multibulk cap; input never mutated) | diff_prims, diff_fold |"
echo "| Runtime_Prims_refines | assumption (tcb-assumption) | apply_prim == Prims.prim_* | diff_prims (3000 pipeline states G1-G16 + direct per-prim pass, all 16 prims; R12 case folds exhaustive over all 256 single bytes + ci-dispatch pipeline C1-C5; R13 snoc value-asserted incl. large/nested) + diff_fold (R13 collecting fold over fuzzed stores, M1-M7) |"
echo "| Runtime_Fold_refines | assumption (tcb-assumption) | Fold -> List.fold_left, [acc; elem] = db[0; 1]; order/short-circuit/non-list posture | diff_fold (400x5 rounds, F1-F8, order via trace; +300 R13 collecting-fold rounds, M1-M7) |"
echo "| Journal (Append; buffer + optional sink, shared time source) | effect | Rkv.Journal | diff_journal |"
echo "| Runtime_Journal_refines | assumption (tcb-assumption) | buffer == reference journal (chronological, run-instant timestamps); everything sink-onward (disk bytes, crash atomicity, fsync) is named consumer trust — durability NOT proven | diff_journal (300x3x2, J1-J9: order under Repeat/Fold, short-circuit, sink==buffer, two instants) |"
echo "| value_tag | primitive | Rval.Tag (Z.t, Rval.t) | diff_structval |"
echo "| value_list | primitive | Rval.List (Rval.t list) | diff_structval |"
echo "| Runtime_StructVal_refines | assumption (tcb-assumption) | DTag/DList <-> Rval.Tag/Rval.List bridge + tag_build/tag_dispatch samples | diff_structval (2000+3000 sample states, 2000 fuzzed bridge round-trips, S1-S9 coverage) |"
echo "| Store (Get/Put/Delete/GetDeadline/SetDeadline; bytes keys, live iff now<=d) | effect | Rkv.Kv | diff_test, diff_kv, diff_store |"
echo "| Time (Now; injectable source, wall clock default) | effect | Rkv.Time | diff_time |"
echo "| Runtime_KV_refines | assumption (tcb-assumption) | reference == fast (live bindings, deadlines incl.) | diff_test, diff_kv (5000 adversarial), diff_store (3000; d-1/d/d+1 per key) |"
echo "| Runtime_SingleTimeSource_refines | assumption (tcb-assumption) | store-now == time-now, one source instance; test source steps only between runs | diff_time (3000; reference-now == fast-source-now per run) |"
echo "| Error (Throw) | effect | Rkv.Err | diff_err |"
echo "| Runtime_Error_refines | assumption (tcb-assumption) | abort outcome+state | diff_err (3000) |"
echo "| Env (Ask) | effect | Rkv.Env | diff_env |"
echo "| Runtime_Env_refines | assumption (tcb-assumption) | read-only ctx flows | diff_env (3000) |"
echo "| Trace (Emit) | effect | Rkv.Trace | diff_trace |"
echo "| Runtime_Trace_refines | assumption (tcb-assumption) | event log in order | diff_trace (3000) |"
echo "| Cache (CGet/CPut) | effect | Rkv.Cache | diff_cache |"
echo "| Runtime_Cache_invisible | assumption (tcb-assumption) | hit == miss (invisible) | diff_cache (3000) |"
echo "| Codec | typed-witness realizer (GADT, no casts) | Rkv.Codec | codec_test; proven in Codec.v |"
echo
echo "## Public effectful entrypoints"
echo "- \`Generated.Prog0_generated.prog0\` under \`Rkv.Kv.run\`/\`run_checked\` (unhandled -> typed error, T8)."
echo "- error programs (sample_throw/sample_guard5) under \`Err.run_error (Kv.run …)\` (throw -> Error e, aborts)."
echo
echo "## Forbidden-API gates (CI)"
echo "- no Obj.magic; Effect.perform confined to runtime/; no Admitted/admit/Axiom; no unregistered Extract Constant; generated file unedited."
echo "- codegen wf-gates every program pre-emission with the EXTRACTED, PROVEN well-formedness checker (theories/Wf.v wf_tm, adr-0014 — scope/arity/binder counts; not a new realizer, no opt-out; ill-formed input fails the run loudly)."
} > "$out"
echo "wrote $out"
